// <auto-generated />
using System;
using Agoda.DevExTelemetry.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agoda.DevExTelemetry.Core.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20260824073108_AddCommandEventsAndSessionId")]
    partial class AddCommandEventsAndSessionId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Agoda.DevExTelemetry.Core.Models.Entities.BuildMetric", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitSha")
                        .HasColumnType("TEXT");

                    b.Property<int>("CpuCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutionEnvironment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDebuggerAttached")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReloadType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEndpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TimeTakenMs")
                        .HasColumnType("REAL");

                    b.Property<string>("ToolVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildCategory");

                    b.HasIndex("ExecutionEnvironment");

                    b.HasIndex("MetricType");

                    b.HasIndex("ProjectName");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("SessionId");

                    b.ToTable("BuildMetrics");
                });

            modelBuilder.Entity("Agoda.DevExTelemetry.Core.Models.Entities.CommandEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ColdInstall")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitSha")
                        .HasColumnType("TEXT");

                    b.Property<int>("CpuCount")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DomContentLoadedMs")
                        .HasColumnType("REAL");

                    b.Property<int?>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtraData")
                        .HasColumnType("TEXT");

                    b.Property<double?>("FirstContentfulPaintMs")
                        .HasColumnType("REAL");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LockfileChanged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MeasurementSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageManager")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageManagerVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Prebundled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Signal")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEndpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SpooledAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TimeTakenMs")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementSource");

                    b.HasIndex("Phase");

                    b.HasIndex("ProjectName");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("SessionId");

                    b.HasIndex("SourceEndpoint");

                    b.ToTable("CommandEvents");
                });

            modelBuilder.Entity("Agoda.DevExTelemetry.Core.Models.Entities.CommandEventNpmTimer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandEventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationMs")
                        .HasColumnType("REAL");

                    b.Property<string>("TimerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommandEventId");

                    b.HasIndex("TimerName");

                    b.ToTable("CommandEventNpmTimers");
                });

            modelBuilder.Entity("Agoda.DevExTelemetry.Core.Models.Entities.RawPayload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RawPayloads");
                });

            modelBuilder.Entity("Agoda.DevExTelemetry.Core.Models.Entities.TestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassName")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("REAL");

                    b.Property<string>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MethodName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestRunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassName");

                    b.HasIndex("Status");

                    b.HasIndex("TestRunId");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("Agoda.DevExTelemetry.Core.Models.Entities.TestRun", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CpuCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutionEnvironment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FailedTests")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDebuggerAttached")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PassedTests")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SkippedTests")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceEndpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestRunner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TotalDurationMs")
                        .HasColumnType("REAL");

                    b.Property<int?>("TotalTests")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionEnvironment");

                    b.HasIndex("ProjectName");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("TestRunner");

                    b.ToTable("TestRuns");
                });

            modelBuilder.Entity("Agoda.DevExTelemetry.Core.Models.Entities.CommandEventNpmTimer", b =>
                {
                    b.HasOne("Agoda.DevExTelemetry.Core.Models.Entities.CommandEvent", "CommandEvent")
                        .WithMany("NpmTimers")
                        .HasForeignKey("CommandEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommandEvent");
                });

            modelBuilder.Entity("Agoda.DevExTelemetry.Core.Models.Entities.TestCase", b =>
                {
                    b.HasOne("Agoda.DevExTelemetry.Core.Models.Entities.TestRun", "TestRun")
                        .WithMany("TestCases")
                        .HasForeignKey("TestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestRun");
                });

            modelBuilder.Entity("Agoda.DevExTelemetry.Core.Models.Entities.CommandEvent", b =>
                {
                    b.Navigation("NpmTimers");
                });

            modelBuilder.Entity("Agoda.DevExTelemetry.Core.Models.Entities.TestRun", b =>
                {
                    b.Navigation("TestCases");
                });
#pragma warning restore 612, 618
        }
    }
}
